### ISSUE TITLE
Installing on Debian

### ISSUE THREAD

**Issue by GGMethos** [erkin/ponysay#180]
Creating uncompressed zip file ponysay.zip with files from src: __main__.py common.py ponysay.py argparser.py balloon.py backend.py colourstack.py ucs.py spellocorrecter.py kms.py list.py metadata.py ponysaytool.py
gzip -9 -f < manuals/manpage.6.install > manuals/manpage.6.gz
makeinfo manuals/ponysay.texinfo
sh: 1: makeinfo: not found
gzip -9 -f < ponysay.info > ponysay.info.gz
Traceback (most recent call last):
  File "./setup.py", line 1188, in <module>
    Setup()
  File "./setup.py", line 290, in __init__
    self.build(conf)
  File "./setup.py", line 465, in build
    compress('ponysay.info', 'ponysay.info.' + ext, ext)
  File "./setup.py", line 371, in compress
    filein = open(source, 'r')
IOError: [Errno 2] No such file or directory: 'ponysay.info'

Bug?

**Comment by JoeGlancy** [comment]
Same error here. Fixed or unxifed?

**Comment by jristz** [comment]
install makefile and texinfo, als use the last git push.
