### ISSUE TITLE
error at build because ponysay.info

### ISSUE THREAD

**Issue by JotaRandom** [erkin/ponysay#188]
´´´´
gzip -9 -f < ponysay.info > ponysay.info.gz
Traceback (most recent call last):
  File "./setup.py", line 1188, in <module>
    Setup()
  File "./setup.py", line 281, in **init**
    self.build(conf)
  File "./setup.py", line 465, in build
    compress('ponysay.info', 'ponysay.info.' + ext, ext)
  File "./setup.py", line 371, in compress
    filein = open(source, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'ponysay.info'
./setup.py build --freedom=partial  8,02s user 0,19s system 76% cpu 10,772 total
´´´´
Well aparently something change in ponysay.info or ponysay.texinfo?
I know what to do, but I wnat know if now is ponysay.texinfo or ponysay.info, because I not remmember changin' it

**Comment by brian-lamb-software-engineer** [comment]
seems this is an ongoing error.  Im not able to get it to run.  i have tried compiling with python36, but when i do a `phtyon -v` it says its still 2.75.  Im trying to build like this `python36 ./setup.py --freedom=strict --private install` . but have tried all the rest in the documentation also.
