### ISSUE TITLE
Errno 2: ponysay.info and Errno 36: Filename too long

### ISSUE THREAD

**Issue by essence-of-orange** [erkin/ponysay#191]
The ponysay.info bug is still hanging around. I can't get any of the recent releases to build straight off the bat. I "solved" the problem by changing the ponysay.info.gz to just .info but then it runs into another error:

OSError: [Errno 36] File name too long: 'quotes/pinkie+pinkiecannonfront+pinkiecannon+pinkiebounce+pinkiecannonhappy+pinkiegala+pinkiechicken+pinkiehugfluttershy+pinkiegummy+pinkietongue+pinkiesilly.2'

Seems a shame if this has been abandoned, it's a lovely little utility otherwise.

**Comment by laanwj** [comment]
Same problem here - latest git, Ubuntu 14.04, install --private:
```
Traceback (most recent call last):
  File "setup.py", line 1231, in <module>
    Setup()
  File "setup.py", line 296, in __init__
    self.install(conf)
  File "setup.py", line 651, in install
    self.cp(True, dir[0], [ponyshare + dir[0]], Setup.validateFreedom if self.free else None)
  File "setup.py", line 887, in cp
    self.cp(os.path.isdir(src), src, [dest + '/' + file], validatehook)
  File "setup.py", line 900, in cp
    shutil.copyfile(source, dest)
  File "/usr/lib/python3.4/shutil.py", line 108, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 36] File name too long: '.../.local/share/ponysay/quotes/pinkie+pinkiepartycannon+pinkieprincess+pinkiehugsfluttershy+pinkiewhoops+oinkoinkoink+pinkiewhoopsout+pinkiewhoopseat+fillypinkie+fillypinkiecurly+pinkieoink.32'
```
Even after following the workaround and deleting the pinkie ponies:
```
OSError: [Errno 36] File name too long: '....local/share/ponysay/quotes/rainbow+rainbowdrag+rainbowfly+rainbowgala+rainbowsalute+rainbowsleep+fillydashfly+fillydash+rainbowhurricane+rainbowshadowbolt+rainbowdashcrystal+rainbowfim.3'
```

**Comment by JockeTF** [comment]
Are you using ecryptfs?

**Comment by laanwj** [comment]
That was it. Tried installing to a location outside ecryptfs and it worked fine.

**Comment by jristz** [comment]
I going to close this bug since is fixed, we just now need document (or prevent the overlylong pinkiequotes or just plain rewrite the wuote think) the issue.

If any object just ask for reopen (or plain reopen the bug)

**Comment by undermink** [comment]
Just had the same problem. But trying it outside of encryptfs worked for me, too :)
