### ISSUE TITLE
Pony request: Velvet Remedy a la Fallout Equestria

### ISSUE THREAD

**Issue by skyhighwings** [erkin/ponysay#197]
Possible spoilers: http://falloutequestria.wikia.com/wiki/Velvet_Remedy

References:
- https://derpiboo.ru/626610?scope=scpe405c78eea44af6af947230fd2e0a40dc24a7b82d
- https://derpiboo.ru/568319?scope=scpe405c78eea44af6af947230fd2e0a40dc24a7b82d
- https://derpiboo.ru/564072?scope=scpe405c78eea44af6af947230fd2e0a40dc24a7b82d
- https://derpiboo.ru/331452?scope=scpe405c78eea44af6af947230fd2e0a40dc24a7b82d
- https://derpiboo.ru/49875?scope=scpe405c78eea44af6af947230fd2e0a40dc24a7b82d

Thanks for consideration!

**Comment by jristz** [comment]
Look at Pull Request 4 for the pony.
I plain totally forgot this bug, sorry.

Was not merged since I need a little of info first to fill the metadata.

**Comment by skyhighwings** [comment]
Thank you!!!
