### ISSUE TITLE
Error installing on Fedora

### ISSUE THREAD

**Issue by chrismcfee** [erkin/ponysay#207]
::Compiling...
Creating uncompressed zip file ponysay.zip with files from src: colourstack.py common.py kms.py lists.py metadata.py ponysaytool.py ucs.py spellocorrecter.py balloon.py ponysay.py backend.py **main**.py argparser.py
gzip -9 -f < manuals/manpage.6.install > manuals/manpage.6.gz
makeinfo manuals/ponysay.texinfo
sh: makeinfo: command not found
gzip -9 -f < ponysay.info > ponysay.info.gz
Traceback (most recent call last):
  File "setup.py", line 1187, in <module>
    Setup()
  File "setup.py", line 280, in **init**
    self.build(conf)
  File "setup.py", line 464, in build
    compress('ponysay.info', 'ponysay.info.' + ext, ext)
  File "setup.py", line 370, in compress
    filein = open(source, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'ponysay.info'

**Comment by maxlefou** [comment]
Had this issue as well. Installing texinfo as mentionned fixed it.

It would be a good thing to add this in the dependency check script. ;)
