### ISSUE TITLE
Build fails if optional dependency "texinfo" is not installed

### ISSUE THREAD

**Issue by DuckThom** [erkin/ponysay#218]
When running ./dependency-test.sh it returns:

`Missing makeinfo, install texinfo [build optional]`

But when I try to build it, it will fail with the following error:

    Traceback (most recent call last):
      File "./setup.py", line 1231, in <module>
        Setup()
      File "./setup.py", line 294, in __init__
        self.build(conf)
      File "./setup.py", line 476, in build
        compress('ponysay.info', 'ponysay.info.' + ext, ext)
      File "./setup.py", line 382, in compress
        filein = open(source, 'r')
    FileNotFoundError: [Errno 2] No such file or directory: 'ponysay.info'

After installing the "optional" dependency it will successfully build.
`sudo apt-get install texinfo`

**Comment by jristz** [comment]
try pass “--without-info-install” to ./setup.py alongside your other
options, this will skip infopage and therefor not need texinfo.

2015-03-17 12:17 GMT-03:00 Thomas Wiringa <notifications@github.com>:

> When running ./dependency-test.sh it returns:
>
> Missing makeinfo, install texinfo [build optional]
>
> But when I try to build it, it will fail with the following error:
>
> Traceback (most recent call last):
>   File "./setup.py", line 1231, in <module>
>     Setup()
>   File "./setup.py", line 294, in __init__
>     self.build(conf)
>   File "./setup.py", line 476, in build
>     compress('ponysay.info', 'ponysay.info.' + ext, ext)
>   File "./setup.py", line 382, in compress
>     filein = open(source, 'r')
> FileNotFoundError: [Errno 2] No such file or directory: 'ponysay.info'
>
> After installing the "optional" dependency it will successfully build.
> sudo apt-get install texinfo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erkin/ponysay/issues/218>.
>



-- 
*Pablo Lezaeta*
