### ISSUE TITLE
Ponies that don't print the message

### ISSUE THREAD

**Issue by izabera** [erkin/ponysay#221]
I just wanted to let you know that cocoachill, oscura and riverbeauty don't
print the message.

**Comment by CrazyPython** [comment]
Any updates from project owners?

**Comment by jristz** [comment]
Thanks for tell us, I going to check those (since I draw Cocoachill and Riverveauty) and compare, probably I miss a controll code or a metadata.

**Comment by jristz** [comment]
$balloon30$^[[00m
was missing from those files, in theory they now should show the baloon.
