### ISSUE TITLE
Where is Fluffle Puff?

### ISSUE THREAD

**Issue by MayakoLyyn** [erkin/ponysay#222]
Heyyy. I just discovered ponysay and I see that Fluffle Puff isn't on your list. This isn't a canon pony but she's quite popular among the fanbase.

Is it possible to add her? ♥

**Comment by jristz** [comment]
test “ponysay -o -F fluffle” and show us the output

**Comment by MayakoLyyn** [comment]
Oops. Didn't see your reply. I tried and it shows me Fluffle. So... Sorry for my useless request ^^'

I really didn't see her in the list :<

**Comment by jristz** [comment]
That becausr she is in the OC list, there is a second list, check - - help
for more info

**Comment by MayakoLyyn** [comment]
Yup, I tried "ponysay -A" but I misread the lists I think ^^'
