### ISSUE TITLE
Incorrect display of balloon

### ISSUE THREAD

**Issue by kenzierocks** [erkin/ponysay#227]
I just merged master into my [fork](https://github.com/kenzierocks/ponysay), and now balloons are strange:
![picture of strange balloons](https://i.imgur.com/OpJxqsC.png)

**Comment by jristz** [comment]
do you could tell the the parent commit or the last change you did, to look where to start.
Here in my sistem aside from a few ponies with baloon problems (mostly from the OC list) all are ok.

**Comment by kenzierocks** [comment]
It's the latest merge commit. Also, it only seems to occur with Unicode
bubbles.

On Monday, October 12, 2015, Pablo Lezaeta Reyes [pˈaβ̞lo lˌe̞θaˈeta rˈejɛ]
<notifications@github.com> wrote:

> do you could tell the the parent commit or the last change you did, to
> look where to start.
> Here in my sistem aside from a few ponies with baloon problems (mostly
> from the OC list) all are ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erkin/ponysay/issues/227#issuecomment-147493224>.
>


-- 
~Kenzie Togami

**Comment by kenzierocks** [comment]
As of 42280dbdb5f1c2b0bdd5b84aed8e63c0b6bda731 this is still a problem with nested balloons. It seems the width calc is incorrect, resulting in too little spaces on multibyte characters.
