### ISSUE TITLE
Install failure with symlink already present

### ISSUE THREAD

**Issue by kenzierocks** [erkin/ponysay#228]
Fresh install, `sudo ./setup.py install --freedom=partial --with-everything`: https://gist.github.com/kenzierocks/c78a437d2e12a87c55af#file-install-log-L1048
On Ubuntu 14.04.

**Comment by random-access** [comment]
I got exactly the same error on Ubuntu 15.10 with a fresh install.

**Comment by JoeGlancy** [comment]
See issue #229 - I think it's the same issue. I've submitted a pull request which should fix this issue: https://github.com/erkin/ponysay/pull/231.

**Comment by jristz** [comment]
please any info if the "new" (is like 2 months old) pull now fix the issue?

**Comment by kenzierocks** [comment]
This has been fixed with the merge of #231.
