### ISSUE TITLE
Add height parameter for random ponies

### ISSUE THREAD

**Issue by zidarsk8** [erkin/ponysay#234]
Is it possible to add a max height argument to ponysay so that those really big ones won't appear? Something like: `ponysay -h 23 "This is now 20% cooler"` and it would only dispaly a pony if it's 23 or less characters tall (the height in the ponyfile)

**Comment by maandree** [comment]
Try `-r height=23`. If you want a range, you could do `-rheight={23..30}`, for example. In the latter case, it is important that there are no spaces, otherwise the expression is expanded in the wrong way.

**Comment by zidarsk8** [comment]
This is awesome, thanks.

It would be nice if the `-r` was better documented as to what the names and values can be, but I guess i should have been able to figure it out.

**Comment by maandree** [comment]
I guess the documentation could be more clear about the keys being the metadata keys, and include a referense to the metadata section (`info '(ponysay)' 'pony metadata'`).
