### ISSUE TITLE
  // , Installation fails on CEntOS 7. 

### ISSUE THREAD

**Issue by v6** [erkin/ponysay#235]
// , 

The file `ponysay.info` is missing. 

The code I got is as follows: 

    [vagrant@localhost ponysay]$ sudo python3 ./setup.py --freedom=partial install
    Installing command ponysay as /usr/bin/ponysay
    Installing command ponythink as /usr/bin/ponythink
    Installing command ponysay-tool as /usr/bin/ponysay-tool
    Installing shared cache at /var/cache/ponysay
    Installing auto-completion for bash as /usr/share/bash-completion/completions/ponysay
    Installing auto-completion for fish as /usr/share/fish/completions/ponysay.fish
    Installing auto-completion for zsh as /usr/share/zsh/site-functions/_ponysay
    Skipping installation of PDF manual
    Skipping compression of PDF manual
    Installing info manual to /usr/share/info
    Installing info manual with install-info with description: My Little Ponies for your terminal
    Compressing info manual with gz
    Installing English manpage to /usr/share/man
    Compressing English manpage with gz
    Skipping installation of Spanish manpage
    Compressing Spanish manpage with gz
    Skipping installation of Swedish manpage
    Compressing Swedish manpage with gz
    Skipping installation of Turkish manpage
    Compressing Turkish manpage with gz
    References to manpage for ponysay points to section 6
    References to manpage for cowsay points to section 1
    References to manpage for fortune points to section 6
    Installing xterm ponies to /usr/share/ponysay/ponies
    Installing tty ponies to /usr/share/ponysay/ttyponies
    Installing extra xterm ponies to /usr/share/ponysay/extraponies
    Installing extra tty ponies to /usr/share/ponysay/extrattyponies
    Installing pony quotes to /usr/share/ponysay/quotes
    Installing balloon styles to /usr/share/ponysay/balloons
    Installing ucsmap as /usr/share/ponysay/ucs
    Looking for best env reference in python script shebang
    Installing COPYING to /usr/share/licenses/ponysay/COPYING
    Installing LICENSE to /usr/share/licenses/ponysay/LICENSE
    Installing CREDITS to /usr/share/licenses/ponysay/CREDITS
    Using system configuration directory: /etc
    Prefered linking style: symbolic
    Using umask: 022 (only owner can do modifications)
    Installing not only fully free parts of the package

    ::Compiling...
    Creating uncompressed zip file ponysay.zip with files from src: __main__.py argparser.py backend.py balloon.py colourstack.py common.py kms.py lists.py metadata.py ponysay.py ponysaytool.py spellocorrecter.py ucs.py
    gzip -9 -f < manuals/manpage.6.install > manuals/manpage.6.gz
    makeinfo manuals/ponysay.texinfo
    sh: makeinfo: command not found
    gzip -9 -f < ponysay.info > ponysay.info.gz
    Traceback (most recent call last):
      File "./setup.py", line 1238, in <module>
        Setup()
      File "./setup.py", line 294, in __init__
        self.build(conf)
      File "./setup.py", line 476, in build
        compress('ponysay.info', 'ponysay.info.' + ext, ext)
      File "./setup.py", line 382, in compress
        filein = open(source, 'r')
    FileNotFoundError: [Errno 2] No such file or directory: 'ponysay.info'
    [vagrant@localhost ponysay]$ ls
    balloons   completion    COPYING  dependency-test.sh  extraponies  extrattyponies  manuals  ponyquotes       ponysay.install  ponysay.zip  setup.py  src
    CHANGELOG  CONTRIBUTING  CREDITS  dev                 extras       LICENSE         ponies   ponysay.info.gz  ponysay.pdf      README.md    share     ttyponies
    [vagrant@localhost ponysay]$ gzip -9 -f < ponysay.info > ponysay.info.gz
    -bash: ponysay.info: No such file or directory
    [vagrant@localhost ponysay]$

**Comment by jristz** [comment]
you need install texinfo

what ./dependency-test.sh show to you?

**Comment by v6** [comment]
// , 

    $ ./dependency-test.sh
    Missing ponytool, install util-say [runtime optional]
    
    Everything appears to be in order, enjoy ponysay!


```
$ brew install util-say
Error: No available formula with the name "util-say"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by v6** [comment]
// , 

    $ brew search say
    cowsay                                   ponysay

**Comment by v6** [comment]
// , Should the dependency test have warn automatically? 

Of course, if I had checked https://github.com/erkin/ponysay#package-building-dependencies, I could have solved my own problem, but in the case of people like me, even good documentation often does not solve "PEBKAC" errors.

Close this issue at will.

**Comment by v6** [comment]
// , Is there a Puppet Module or Salt State for ponysay, if I ever need to deploy this to production?

**Comment by maandree** [comment]
Question. Why do you start your posts with `// ,`?

I don't think it is necessary to check the dependencies automatically when the install begins, but perhaps it could be suggested if the install fails.

I like the idea that you would _need_ to deploy this. But I don't know about puppet and salt, sounds like sysadmin stuff. Not really my area. But if you find or make any I'm sure we could list it along with the software reposity listing

**Comment by v6** [comment]
// , Oh, it's **necessary**.

You know what they say about distributed systems. 

> No pony fun? Cluster won't run.
