### ISSUE TITLE
Interactive ponysay

### ISSUE THREAD

**Issue by SpyCheese** [erkin/ponysay#237]
I have an idea about new functionality.
Create a tool to run interactive programs (such as shell or vim) inside the balloon.
Something like that:
![image](https://cloud.githubusercontent.com/assets/11584995/14610894/7ed1260e-05b1-11e6-8c07-b855240bcc76.png)

**Comment by maandree** [comment]
Neat idea, although a lot of waste of screen space. I am closing this as it should not be implemented in the Ponysay repository. It is too large to be implemented in extras/. For anyone seeking to implement this, I would suggest modifying tmux.
