### ISSUE TITLE
Pony not showing correctly on OS X

### ISSUE THREAD

**Issue by zephyrfalcon** [erkin/ponysay#238]
ponysay doesn't seem to render the pony properly on Mac OS X, at least not in the default terminal. Is this simply unsupported/a known problem, or are there certain settings that might change this? As far as I can tell, the terminal on OS X does not support some (most?) of the ANSI codes being used, resulting in displays such as:

<img width="725" alt="screen shot 2016-05-02 at 5 56 06 am" src="https://cloud.githubusercontent.com/assets/55366/14951943/7eb79d28-102a-11e6-92ce-2a9c200792bd.png">

Am I doing something wrong? Is there a way around this?

**Comment by maandree** [comment]
It looks like you have `TERM=linux` in your environment. Try `env TERM=xterm ponysay`. You may also want to change your font to one that have good support for Block Elements.

**Comment by zephyrfalcon** [comment]
Ugh, you are right, I did have TERM=linux in my .zshrc. (I'm not sure why, maybe it originated on Linux and I copied it to OS X at some point, making changes but leaving that setting alone.) In any case, it works now. Thanks for your help! ^_^

**Comment by maandree** [comment]
You probably do not want `TERM=linux` in any file in your system other than /etc/inittab (or corresponding for your init system) on Linux. It indicates that you are running in Linux VT (outside X).
