### ISSUE TITLE
Griffin is not the Griffon term?

### ISSUE THREAD

**Issue by jristz** [erkin/ponysay#242]
Initially we discused like... 3 years ago that we goint to use Griffin to define this specie but look like we were wrong (or the _sic_ go so far) since we have now
- Griff**on**stone
- Griff**on** the brush off
- Griff**on** as the name used in the Gamleoft Game
- Griff**on** used in the Enterplay Trading Card Game
- Griff**on** used in official merchandise from Hasbro
- Griff**on** used on the hasbro mlp page
- Griff**on** used on the mlp wiki

So unless the mistypo go really **FAR** I think griff_on_ is the mlp term for griffin, we need remember that the mlp 'verse don't use the same words as us, right every_pony_?

So the wuestion is: Remove the _(sic!)_ from the chapter name and fix the few griffin references on the ponyfiles and the manual and info pages?

**Comment by maandree** [comment]
Sounds like the proper thing to do.

**Comment by jristz** [comment]
I think I cover all the strings so far, if some string get missing let open new bugs, so for now this is fixed and griffon now the official.
