### ISSUE TITLE
Starlightglimmer missing balloon

### ISSUE THREAD

**Issue by matsjoyce** [erkin/ponysay#244]
See https://github.com/erkin/ponysay/blob/master/ponies/starlightglimmer.pony#L20-L22. There is no balloon specified so you get (no quote):
![screenshot_20161202_131106](https://cloud.githubusercontent.com/assets/6631310/20835143/d8e95dea-b890-11e6-990a-0bbae1896fef.png)

**Comment by jristz** [comment]
As in issue #221 there is a few ponies without the $baloon string, we have som many that we keep missing some ponies.

thanks I will check the pony for the missing baloon when I get the time (soon).

**Comment by matsjoyce** [comment]
```bash
[matthew@matthew-laptop {master} ponysay]$ grep -rL "balloon" ponies/
ponies/starlightglimmer.pony
[matthew@matthew-laptop {master} ponysay]$ grep -rL "balloon" extraponies/
extraponies/metadata
[matthew@matthew-laptop {master} ponysay]$ grep -rL "balloon" ttyponies/
ttyponies/starlightglimmer.pony
[matthew@matthew-laptop {master} ponysay]$ grep -rL "balloon" extrattyponies/
extrattyponies/metadata
```
From my grepping, Starlightglimmer is the last one.
