### ISSUE TITLE
Ponysay doesn't work with xonsh

### ISSUE THREAD

**Issue by moigagoo** [erkin/ponysay#249]
[Xonsh](http://xon.sh) is a Python-based shell. Ponysay doesn't show any ponies in it on Mac OS. Instead, there are just empty lines.

The issue has already been reported in xonsh's repo: https://github.com/xonsh/xonsh/issues/2115

**Comment by jristz** [comment]
Confirmed, even in linux xonsh not show anypony indiferent the terminal used.

**Comment by jristz** [comment]
looking the bug look like is an issue in xosh and was fixed, so unless someone still have problems I will put an close to this.

Reopening by request for now.
