### ISSUE TITLE
~/.ponysayrc link on website 404 not found

### ISSUE THREAD

**Issue by benknoble** [erkin/ponysay#253]
On the [ponysay site](http://erkin.co/ponysay/), if I go to *Advanced Usage* and click `~/.ponysayrc` I'm met with a 404 error from GH Pages.

I looked in other issues and couldn't find anything related.

**Comment by jristz** [comment]
Ho, Well no one has touched the webpage since... like... latest 2.x which was when season 2 or 3 was on air

i think the error is because it try to parse ~/.ponysayrc as a link which you cant because ~/. will mess all.

**Comment by jristz** [comment]
The branch is https://github.com/erkin/ponysay/tree/gh-pages I think and like you see was not touched since 2013...

I _maybe_ will check it but no promises since I have never touched that branch
