### ISSUE TITLE
Document Windows Subsystem for Linux support?

### ISSUE THREAD

**Issue by ngyikp** [erkin/ponysay#255]
It took [Microsoft some time](https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/), but Windows 10 is _finally_ ready for serious pony development 🚀 

![](https://cloud.githubusercontent.com/assets/6135313/26415714/0e7b4580-40e6-11e7-83ae-3f4b833e1be2.png)

**Comment by jristz** [comment]
yeah document it.
just keep the same style... later someonther could tweak the thing
