### ISSUE TITLE
Update readme to reflect configure changes please

### ISSUE THREAD

**Issue by MrOnosa** [erkin/ponysay#258]
`./configure --without-info` does not work but `./setup.py --without-info --freedom=partial install` worked just fine.

**Comment by jristz** [comment]
verbatim from the README.md

> Download or clone the project. In the terminal, cd into the ponysay directory and ./setup.py --freedom=partial install or python3 setup.py --freedom=partial install.

so which file exactly do you talk?

**Comment by MrOnosa** [comment]
I am discussing the the `--without-info` configuration flag.

**Comment by jristz** [comment]
`--without-info` use `texinfo` to build the info pages and is listed as dep on the dependency test `./dependency-test.sh`
also in the `README.md` in the section **Dependencies **>** Package building dependencies** mention t`exinfo` too.

Maybe move the section **Dependency** above or within **Installation on GNU/Linux**.

**Comment by jristz** [comment]
I move the dependency to the first; let me know if that make it clearer on what is need.

**Comment by jristz** [comment]
I will close it since now the first paragraft show what is need.

also `./dependency-list.sh` will show if youmeet all the deps, if it not with the defaukt flags and installing it then fill a bug aagainst the dep-check to get updated (and by extention the `Readme.md`)
