### ISSUE TITLE
Installing on Ubuntu 19.10 requires texinfo.

### ISSUE THREAD

**Issue by DDR0** [erkin/ponysay#300]
```
sudo apt-get install texinfo
```
is required to fix
```
::Compiling...
Creating uncompressed zip file ponysay.zip with files from src: argparser.py lists.py colourstack.py ponysay.py balloon.py backend.py common.py kms.py ucs.py ponysaytool.py __main__.py metadata.py spellocorrecter.py
gzip -9 -f < manuals/manpage.6.install > manuals/manpage.6.gz
makeinfo manuals/ponysay.texinfo
sh: 1: makeinfo: not found
gzip -9 -f < ponysay.info > ponysay.info.gz
Traceback (most recent call last):
  File "./setup.py", line 1239, in <module>
    Setup()
  File "./setup.py", line 295, in __init__
    self.build(conf)
  File "./setup.py", line 477, in build
    compress('ponysay.info', 'ponysay.info.' + ext, ext)
  File "./setup.py", line 383, in compress
    filein = open(source, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'ponysay.info'
```
so the install is not quite as simple as in the README.

**Comment by adasiko** [comment]
README.md

> Package building dependencies
> 
> gzip: Used for compressing manuals (suppressable with ./configure --without-info-compression --without-man-compression).
> 
> texinfo: Used for building the info manual (suppressable with ./configure --without-info).
> 
> python>=3: The installation process is written in Python 3.
> 
> Run ./dependency-test.sh if things are not working for you.

**Comment by DDR0** [comment]
Oh, so that's ... oh, I see now. Not for building _the package_, but for _building_ the package.
