### ISSUE TITLE
How can I add ponies?

### ISSUE THREAD

**Issue by elpideus** [erkin/ponysay#308]
Hi, I'm not really that good at coding but I like to draw pixel art. I would really like to create something and contribute to this project. But I do not understand how must I write the color codes and test them.

**Comment by matthias4217** [comment]
Hello, there are some instructions in the [pdf documentation](https://raw.githubusercontent.com/erkin/ponysay/master/ponysay.pdf#Providing%20ponies). What you roughly need to do is the following :
1. Create the picture and export it as a PNG file.
2. Install `util-say :
    1. If you are running ArchLinux, it's available in the AUR repo, else, you need to clone the [git repository](https://github.com/maandree/util-say)
    2. Execute a `make install` in the repository (you'll need `java-runtime` version 6 minimum and `coreutils`.
3. Convert the picture to a `.pony`  file using `util-say` : `img2ponysay -- SOURCE_IMAGE > PONY_FILE`
4. Then you can display your pony : `ponysay -F PONY_FILE -o`

Then you can edit the metadata, using `ponysay-tool --edit PONY_FILE`.

If you want, I can do the conversion to a pony image for you. However it may be a bit slower as the colors used by terminals are limited, and thus the picture do not reflect exactly the true colors of the original picture. I maintain a repository of non-pony pictures [here](https://framagit.org/matthias4217/custom-ponysay/) if you want to see more.

**Comment by elpideus** [comment]
Thank you so much for your answer.
 I will try to do it all by myself. I already know that the terminal colors are limited, I will try to draw using limited colors.
I will let you know when I'll finish doing my first pony for ponysay.
