### ISSUE TITLE
Flatpak: Free Desktop SDK 19.08 is End of Life

### ISSUE THREAD

**Issue by ChristianSilvermoon** [erkin/ponysay#310]
The following message is presented when installing ponysay via flatpak from flathub
```
Info: org.freedesktop.Platform//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
```

**Comment by kate-shine** [comment]
Hi, the ponysay flatpak package isn't managed by upstream (erkin)

https://github.com/flathub/io.github.erkin.ponysay/pull/2 is fixing this and should get into flathub tomorrow (2022-02-21) at the latest. I suggest closing this issue and if there is another problem with it, please open another issue on that repository :) Thank you ^^

**Comment by ChristianSilvermoon** [comment]
> Hi, the ponysay flatpak package isn't managed by upstream (erkin)
> 
> [flathub/io.github.erkin.ponysay#2](https://github.com/flathub/io.github.erkin.ponysay/pull/2) is fixing this and should get into flathub tomorrow (2022-02-21) at the latest. I suggest closing this issue and if there is another problem with it, please open another issue on that repository :) Thank you ^^

Thanks for the info, I'll try and keep this in mind for the future, thank you ^^
